# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PodClock' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodClock

  target 'PodClockTests' do
	pod ‘Snapkit’
	pod ‘RxSwift’
	pod ‘
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodClockUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
